# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recipe.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("recipe.proto", :syntax => :proto3) do
    add_message "recipe.GetByIdRequest" do
      optional :id, :int32, 1
    end
    add_message "recipe.GetByIdResponse" do
      optional :recipe, :message, 1, "recipe.Recipe"
    end
    add_message "recipe.CreateRecipeRequest" do
      optional :title, :string, 1
    end
    add_message "recipe.CreateRecipeResponse" do
      optional :recipe, :message, 1, "recipe.Recipe"
    end
    add_message "recipe.Recipe" do
      optional :id, :int32, 1
      optional :title, :string, 2
    end
  end
end

module Recipe
  GetByIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("recipe.GetByIdRequest").msgclass
  GetByIdResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("recipe.GetByIdResponse").msgclass
  CreateRecipeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("recipe.CreateRecipeRequest").msgclass
  CreateRecipeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("recipe.CreateRecipeResponse").msgclass
  Recipe = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("recipe.Recipe").msgclass
end
