# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: recipe.proto for package 'coot'

require 'grpc'
require 'recipe_pb'

module Coot
  module RecipeService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'coot.RecipeService'

      rpc :GetById, GetByIdRequest, GetByIdResponse
      rpc :CreateRecipe, CreateRecipeRequest, CreateRecipeResponse
    end

    Stub = Service.rpc_stub_class
  end
end
